#!/usr/bin/env python3
import os
import sys
import filecmp
import shutil
import yaml

class Jconf:
    def __init__(self, args):
        self._validverbs = ["pull", "push"]
        self._homedir = os.path.normpath(os.getenv("HOME"))
        self._verb = ""
        self._simul = False
        self._verbose = False
        self._files = list()
        self.data = list()

        try:
            self.parse_args(args)
        except RuntimeError:
            self.print_usage()
            return

        try:
            fstrm = open("db.yaml")
            idata = list(yaml.load_all(fstrm))
            fstrm.close()
            self.data = self.check_database(idata, self._files)

        except FileNotFoundError:
            print("db.yaml file not found!")
        except RuntimeError as ex:
            print("Database error: ")
            print(ex)

    def parse_args(self, args):
        if len(args) < 2 or (not args[1] in self._validverbs):
            raise RuntimeError()
        self._verb = args[1]
        for arg in args[2:]:
            if arg == "-n":
                self._simul = True
            elif arg == "-v":
                self._verbose = True
            else:
                self._files.append(arg)

    def print_usage(self):
        verbstr = "%s" % self._validverbs[0]
        for v in self._validverbs[1:]:
            verbstr = verbstr + (" | %s" % v)
        print("Usage: jconf {%s} [-n] [-v] [record1] [record2]..." % verbstr)

    def check_database(self, data, files):
        ndata = list()
        for (i,record) in enumerate(data):
            if 'name' not in record:
                raise RuntimeError("Required key 'name' not in record #%u" % (i+1))
            elif 'home' not in record and 'dir' not in record:
                raise RuntimeError("Record '%s' requires a 'home' or 'dir' field" %
                        record['name'])
            else:
                if len(files) == 0 or record["name"] in files:
                    subdir = os.path.join(self._homedir, "." + record["name"])
                    if "dir" in record and not os.path.exists(subdir):
                        if self._simul or self._verbose:
                            print("Creating subdir in HOME: " + subdir)
                        if not self._simul:
                            os.mkdir(subdir)
                    ndata.append(record)
        return ndata

    def go(self):
        for c in self.data:
            n = c['name']
            if self._verbose:
                print("Record '%s': " % n)
            for f in c.get("home", []):
                self.fileop(self._verb,
                    os.path.join(self._homedir, "." + f),
                    os.path.join(n,f)
                )
            for f in c.get('dir', []):
                self.fileop(self._verb,
                    os.path.join(self._homedir, "." + n, f),
                    os.path.join(n,f)
                )

    def fileop(self, verb, home, repo):
        doprint = self._simul or self._verbose
        if verb == 'pull':
            if doprint:
                print("\tpulling %s -> %s" % (home, repo))
            if not self._simul:
                shutil.copy(home, repo)
        elif verb == 'push':
            if doprint:
                print("\tpushing %s -> %s" % (repo, home))
            if not self._simul:
                shutil.copy(repo, home)

def main():
    conf = Jconf(sys.argv)
    conf.go()

if __name__ == "__main__":
    main()
