"---
"  Josh's vimrc
"  [1] bundle installations
"  [2] option setting
"  [3] nonstandard mappings
"  [4] plugin configs
"  [5] visual configs
"---

set nocompatible
if has("unix")
    set shell=bash
endif

if has("win32") || has("win64")
    call plug#begin('~/vimfiles/plugs')
else
    call plug#begin('~/.vim/plugs')
endif
Plug 'vim-scripts/moria'
Plug 'vim-scripts/a.vim'
Plug 'vim-scripts/camelcasemotion'
Plug 'vim-scripts/surround.vim'
Plug 'Valloric/YouCompleteMe'
Plug 'jlanzarotta/bufexplorer'
Plug 'scrooloose/nerdtree'
Plug 'easymotion/vim-easymotion'
Plug 'benmills/vimux'
Plug 'michaeljsmith/vim-indent-object'
Plug 'JuliaLang/julia-vim'
Plug 'tpope/vim-fugitive'
Plug 'lervag/vimtex'
Plug 'dag/vim-fish'
Plug 'ntpeters/vim-better-whitespace'
call plug#end()

"---
"vim options
"---
filetype plugin indent on

set nobackup
set writebackup
set expandtab
set tabstop=4
set shiftwidth=4

set nosmartindent
set cindent
set backspace=indent,eol,start
set hlsearch
set incsearch
set iskeyword=@,48-57,192-255 "Allow underscore to separate word objects
set nrformats+=alpha "Allow Ctrl-[ax] to work on letters
set foldmethod=indent
set foldnestmax=2

syntax on
"syntax highlighting for ROS launch files
autocmd BufNewFile,BufRead *.launch set filetype=xml
autocmd BufNewFile,BufRead *.jl set filetype=julia

"---
"mappings
"---
"Never move up to press escape!
"inoremap <C-Space> <Esc>
inoremap jk <Esc>

"Alternate colon mapping
noremap <Space> :

"Add empty lines without leaving normal mode
nmap <M-o> o<Esc>0
nmap <M-O> O<Esc>0

"Unhighlight current search results (can still hit 'n' to bring back)
nmap <silent> <Return> :nohlsearch<CR>

"Close preview windows
nmap <silent> <BS><BS> :pclose<CR>

"Add single chars and stay in normal mode
nmap <silent> <M-a> :execute "normal a".nr2char(getchar())."\e"<CR>
nmap <silent> <M-A> :execute "normal A".nr2char(getchar())."\e"<CR>
nmap <silent> <M-i> :execute "normal i".nr2char(getchar())."\e"<CR>
nmap <silent> <M-I> :execute "normal I".nr2char(getchar())."\e"<CR>

"Change default fold opening/closing
nnoremap zo zO
nnoremap zO zo
nnoremap zc zC
nnoremap zC zc

"---
"plugin configs
"---
"Some plugin configs
"NERD Tree
nmap <F2> :NERDTreeToggle<CR>

"a.vim
let g:alternateNoDefaultAlternate = 1
"julia unicode input
let g:latex_to_unicode_auto = 1
"eclim + YCM
let g:EclimCompletionMethod = 'omnifunc'

"---
"visuals
"---
set termguicolors
set ruler
set number
colorscheme moria
set background=dark
set colorcolumn=81
